version: "3.0"
services:
  web:
    build: .
    environment:
      DATABASE_URL: "postgres://user:password@postgres:5432/database"
      SESSION_SECRET: "secret"
      ADMIN_PASSWORD: "admin"
      SEQUELIZE_LOGGING: 1
      ORIGINS: "http://localhost:8080"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    links:
      - postgres
  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "database"
